FROM node:22-bookworm
# Installing promise-retry is a temp fix to be able to upgrade.
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		gnupg \
		lsb-release \
		git \
	&& mkdir -p /etc/apt/keyrings \
	&& curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg \
	&& chmod go+r /etc/apt/keyrings/microsoft.gpg \
	&& AZ_DIST_CODENAME="$(lsb_release -cs)" \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ ${AZ_DIST_CODENAME} main" > /etc/apt/sources.list.d/azure-cli.list \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends azure-cli \
	&& npm install -g promise-retry npm@latest \
	&& npm uninstall -g promise-retry \
	&& rm -rf /var/lib/apt/lists/*